# Generated by Django 4.2.2 on 2023-11-28 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0047_tournament_match_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pool",
            name="sequence_number",
        ),
        migrations.RemoveField(
            model_name="positionpool",
            name="sequence_number",
        ),
    ]
